// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dynamic

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
)

// NewInterface creates a new instance of Interface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *Interface {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Interface{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

type Interface_Expecter struct {
	mock *mock.Mock
}

func (_m *Interface) EXPECT() *Interface_Expecter {
	return &Interface_Expecter{mock: &_m.Mock}
}

// Resource provides a mock function for the type Interface
func (_mock *Interface) Resource(resource schema.GroupVersionResource) dynamic.NamespaceableResourceInterface {
	ret := _mock.Called(resource)

	if len(ret) == 0 {
		panic("no return value specified for Resource")
	}

	var r0 dynamic.NamespaceableResourceInterface
	if returnFunc, ok := ret.Get(0).(func(schema.GroupVersionResource) dynamic.NamespaceableResourceInterface); ok {
		r0 = returnFunc(resource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dynamic.NamespaceableResourceInterface)
		}
	}
	return r0
}

// Interface_Resource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resource'
type Interface_Resource_Call struct {
	*mock.Call
}

// Resource is a helper method to define mock.On call
//   - resource schema.GroupVersionResource
func (_e *Interface_Expecter) Resource(resource any) *Interface_Resource_Call {
	return &Interface_Resource_Call{Call: _e.mock.On("Resource", resource)}
}

func (_c *Interface_Resource_Call) Run(run func(resource schema.GroupVersionResource)) *Interface_Resource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 schema.GroupVersionResource
		if args[0] != nil {
			arg0 = args[0].(schema.GroupVersionResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Interface_Resource_Call) Return(namespaceableResourceInterface dynamic.NamespaceableResourceInterface) *Interface_Resource_Call {
	_c.Call.Return(namespaceableResourceInterface)
	return _c
}

func (_c *Interface_Resource_Call) RunAndReturn(run func(resource schema.GroupVersionResource) dynamic.NamespaceableResourceInterface) *Interface_Resource_Call {
	_c.Call.Return(run)
	return _c
}
